# Python Getting started
First question to answer: Python 2 vs Python 3. As Python 2.X support ends in 2020, there barely is any good reason to stick with it. 
Python 3 was introduced in 2008 and was backward-incompatible with previous releases. 

Sources: 
 - 90% of python in 90 minutes : https://www.slideshare.net/MattHarrison4/learn-90
 - w3schools : https://www.w3schools.com/python/
 - list of guides : https://wiki.python.org/moin/BeginnersGuide


In [1]:
# The Zen of python (PEP20)!
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
import antigravity

![title](https://zgab33vy595fw5zq-zippykid.netdna-ssl.com/wp-content/uploads/2017/09/growth_major_languages-1-1400x1200.png
)


![title](https://zgab33vy595fw5zq-zippykid.netdna-ssl.com/wp-content/uploads/2017/09/projections-1-1400x1200.png)

## Basic Python

Python is a dynamically-typed language in comparison to Java which is statically typed. This mainly has an influence on the way we define variables. 
 - Statically a variable name is bound to: Type + Object 
 - Dynamically a variable is only bound to an object
 
 + No compilation needed in a dynamically typed language, instead the code is interpreded

Getting to know the REPL (read, eval, print, loop), command line interface - or use Jupyter notebook!

The core functionality in python is very small. Install and import libraries to extend this functionality.

### A calculator example

In [ ]:
5 + 5 * 2

In [ ]:
import math
math.pow(5, 2)

### Variables
3 types of numeric types in Python
 - int
 - float
 - complex

Another variable type is **strings**

String methods: https://www.w3schools.com/python/python_ref_string.asp

In [3]:
x = 1    # int
y = 2.8  # float
z = 1+2j # complex
print('Converting float {} to int {}'.format(y, int(y)))
type(x)

Converting float 2.8 to int 2


int

In [4]:
mystring1 = 'pattern '
mystring2 = "recognition"
comb = mystring1 + mystring2
print('string is:', comb)
print('string is: ' + comb)
print('string is: %s' % (comb))
print('string is: {}'.format(comb))
print('convert to str: {}, type: {}'.format(str(y), type(str(y))))
type(comb), len(comb)

string is: pattern recognition
string is: pattern recognition
string is: pattern recognition
string is: pattern recognition
convert to str: 2.8, type: <class 'str'>


(str, 19)

### Python operators
Find a comprehensive list of python operators here:
https://www.w3schools.com/python/python_operators.asp
 - and
 - or
 - modulus
 - addition
 - etc.

### Arrays (collections)
https://www.w3schools.com/python/python_lists.asp
- List [] - ordered and changeable and allows duplicates
- Tuple () - ordered and unchangeable and allows duplicates
- Set {} - unordered and changeable and no duplicates
- Dictionary {key: value} - unordered and changeable and indexed and no dublicates

In [5]:
# List
thislist = ["apple", "banana", "cherry"]
print(thislist)
thislist.append(2)
thislist.append("banana")
print(thislist)
print(thislist[0])
thislist[0] = "carrot"
print(thislist)
print(len(thislist))
print(thislist.pop())

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 2, 'banana']
apple
['carrot', 'banana', 'cherry', 2, 'banana']
5
banana


In [10]:
thistuple = ("apple", "banana", "cherry", "banana")
print(thistuple)
print(thistuple[0])
thistuple.append("banana") # cannot append to tuple

('apple', 'banana', 'cherry', 'banana')
apple


AttributeError: 'tuple' object has no attribute 'add'

In [11]:
thisset = {"apple", "banana", "cherry", "banana"}
print(thisset)
thisset.add("carrot")
thisset.add("banana")
print(thisset)
thisset.discard("banana")
print(thisset)

{'apple', 'cherry', 'banana'}
{'apple', 'cherry', 'banana', 'carrot'}
{'apple', 'cherry', 'carrot'}


In [12]:
thisdict1 = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
# Change dictionary
print(thisdict1.keys())
print(thisdict1.values())
thisdict1["year"] = 2018
print(thisdict1.items())
thisdict1["color"] = "red"
print(thisdict1.items())

dict_keys(['brand', 'model', 'year'])
dict_values(['Ford', 'Mustang', 1964])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2018)])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2018), ('color', 'red')])


Often **dictionaries** are used together with another array type like **list**

In [13]:
thisdict2 = {
  "brand": "BMW",
  "model": "X3",
  "color": "black",
  "year": 2013
}

dictlist = [thisdict1, thisdict2]
dictlist

[{'brand': 'Ford', 'color': 'red', 'model': 'Mustang', 'year': 2018},
 {'brand': 'BMW', 'color': 'black', 'model': 'X3', 'year': 2013}]

## Whitespace vs white space
Python uses indentation, 4 spaces or 1 tab
### Conditions

In [18]:
a = 33
if a > 30:
    print("over 30")
elif a == 30:
    print("equal 30")
else:
    print("less than 30")          

over 30


### Loops

In [19]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [20]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [21]:
for (i, x) in enumerate(fruits):
    print(i, x)

0 apple
1 banana
2 cherry


In [22]:
for x in range(2,5):
    print(x)

2
3
4


### Functions

In [25]:
def myfunc1(a, b=2):
    return a+b
print(myfunc1(2))
res = myfunc1(5, 10)
print(res)

4
15


In [26]:
# Return multiple variables
import math

def myfunc2(a, b=2):
    return a+b, math.pow(a,b)

msum, mpow = myfunc2(5, 3)
msum, mpow

(8, 125.0)

### Class

In [29]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def printNameAge(self):
        print("Name: {}, age: {}".format(self.name, self.age))
        
    def __magicInternalHelperFunction__(self):
        return 365.25 * self.age
    
    def printAgeInDays(self):
        print("Age in days approximately: {}".format(self.__magicInternalHelperFunction__()))
        
        
person1 = Person("Adam", 30)
person2 = Person("Peter", 35)
print(person1.name)
print(person1.age)
person1.age = 25
person1.printNameAge()
person1.printAgeInDays()

Adam
30
Name: Adam, age: 25
Age in days approximately: 9131.25


### Modules
A library of code. A built-in module is for example the **math** module or the **platform** module

In [32]:
import platform

print(platform.processor())

# The DIR function
print(dir(platform))
# The help function
print(help(platform))

i386
Help on module platform:

NAME
    platform

MODULE REFERENCE
    https://docs.python.org/3.7/library/platform
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module tries to retrieve as much platform-identifying data as
    possible. It makes this information available via function APIs.
    
    If called from the command line, it prints the platform
    information concatenated as single string to stdout. The output
    format is useable as part of a filename.

CLASSES
    builtins.tuple(builtins.object)
        uname_result
    
    class uname_result(builtins.tuple)
     |  uname_result(system, node, release, version, machine, processor)
     |  
     |  uname_result(system, node, r

### PIP - Pip Installs Packages
A recursive acronym.
A package contains all the files needed for a module.

 - install with **pip install packagename**
 - example: **pip install numpy**
 
 Pip is installed by default in python 3.4 and later.

### Default python functions:
https://www.w3schools.com/python/python_ref_functions.asp

### Imports

In [34]:
import math
import numpy as np
import matplotlib.pyplot as plt
from numpy import array

array([1,2])

array([1, 2])

### Example help for exercise 2
We will be using numpy for numerical operations.
A numpy array is a grid of values all of the same type.
With numpy it is easy and efficient to perform matrix and vector multiplications.

In [37]:
import numpy as np
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print('a: \n{}'.format(a))
print('b: \n{}'.format(b))
print('mult: \n{}'.format(np.matmul(a,b)))
print('Eye: \n{}'.format(np.eye(3))) # 1 on the diagonal - the identity matrix
print('Zero: \n{}'.format(np.zeros((2,3))))
print('Twos: \n{}'.format(np.ones((2,3))*2))

a: 
[[1, 0], [0, 1]]
b: 
[[4, 1], [2, 2]]
mult: 
[[4 1]
 [2 2]]
Eye: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero: 
[[0. 0. 0.]
 [0. 0. 0.]]
Twos: 
[[2. 2. 2.]
 [2. 2. 2.]]


In [38]:
# Help for future exercises: 
x = np.array([[1,2,3,4,5], [5,4,3,3,2]])
print(x.shape)
y = [1,1,1,-1,-1]
print(type(y))
y = np.array(y)
print(type(y), y.shape)
y = y[:,None]   # Convert the array to a matrix with dimension 1 in one direction (a vector)
print(type(y), y.shape)
yT = np.transpose(y)
yT * x 

(2, 5)
<class 'list'>
<class 'numpy.ndarray'> (5,)
<class 'numpy.ndarray'> (5, 1)


array([[ 1,  2,  3, -4, -5],
       [ 5,  4,  3, -3, -2]])

In [41]:
class MVND:
    def __init__(self, name, data, p=1.0):
        self.name = name
        self.p = p
        self.data = data
        self.sum = np.sum(data)
    def prettyPrintString(self):
        print('MVND with name: {} has sum: {}'.format(self.name, self.sum))
# create a list of objects
gmms = []
gmms.append(MVND('MyMVND1', [1,2,3]))
gmms.append(MVND('MyMVND2', [3,4,5]))
for gmm in gmms:
    print(gmm.name, gmm.sum)
    
for gmm in gmms:
    gmm.prettyPrintString()

MyMVND1 6
MyMVND2 12
MVND with name: MyMVND1 has sum: 6
MVND with name: MyMVND2 has sum: 12
